package dao_dn;
// Generated 03/02/2014 03:55:21 PM by Hibernate Tools 3.6.0



/**
 * Extra generated by hbm2java
 */
public class Extra  implements java.io.Serializable {


     private Integer codExtra;
     private String codigo;
     private String letra;
     private Integer numero;
     private Double decimal;
     private String observacion;
     private String registro;

    public Extra() {
    }

	
    public Extra(String registro) {
        this.registro = registro;
    }
    public Extra(String codigo, String letra, Integer numero, Double decimal, String observacion, String registro) {
       this.codigo = codigo;
       this.letra = letra;
       this.numero = numero;
       this.decimal = decimal;
       this.observacion = observacion;
       this.registro = registro;
    }
   
    public Integer getCodExtra() {
        return this.codExtra;
    }
    
    public void setCodExtra(Integer codExtra) {
        this.codExtra = codExtra;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getLetra() {
        return this.letra;
    }
    
    public void setLetra(String letra) {
        this.letra = letra;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Double getDecimal() {
        return this.decimal;
    }
    
    public void setDecimal(Double decimal) {
        this.decimal = decimal;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


